# Generated by Django 3.1.1 on 2020-10-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_specialprices_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialPrices',
            new_name='SpecialPrice',
        ),
    ]
