# Generated by Django 3.1.1 on 2020-10-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20201001_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialprice',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='listing.listing'),
        ),
    ]
