# Generated by Django 3.1.1 on 2020-10-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20201002_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialprice',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AddConstraint(
            model_name='specialprice',
            constraint=models.UniqueConstraint(fields=('id', 'date'), name='One special price per date'),
        ),
    ]
